---
- name: update du cache
  apt:
   update_cache: yes

- name: installation php7.4
  apt:
   name: php7.4
   state: present

- name : installation fonction php
  apt:
   name: "{{ item }}"
   state: present
  with_items: "{{ php_packages }}"
